version: '3.3'

services:

  redis:
    image: redis
    expose:
      - "6379"

  db:
    image: postgres
    env_file:
      - .env.db
    expose:
      - "5432"

  catalogo:
    build: catalogo
    depends_on:
      - db
      - redis
    image: catalogo:latest
    working_dir: /local/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_USERNAME=dbuser
      - DB_PASSWORD=secreto
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db 
    env_file:
      - .env.catalogo
    volumes:
      - ./catalogo/app:/local/app
    ports:
      - "5000:5000"
